NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.asu.edu-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.asu.edu-cert.pem
    OrganizationalUnitIdentifier: peer
